server:
  port: 8762

spring:
  application:
    # 配合测试相同服务的负载均衡
#    name: service-hello
    # 配合测试不同服务的动态调用
    name: service-hello-a

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/